# Generated by Django 4.2.3 on 2023-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
