# Generated by Django 4.2.3 on 2023-07-11 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_likes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 10, 20, 47, 63919, tzinfo=datetime.timezone.utc)),
        ),
    ]
