# Generated by Django 4.2.3 on 2023-07-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_likes_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='post',
            name='imestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 10, 21, 22, 795559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 10, 21, 22, 795836, tzinfo=datetime.timezone.utc)),
        ),
    ]
