# Generated by Django 4.2.3 on 2023-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_imestamp_post_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
