# Generated by Django 4.2.3 on 2023-07-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_likes_timestamp_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('following', 'follower')},
        ),
    ]
