# Generated by Django 4.2.3 on 2023-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='timestamp',
        ),
    ]
